let knight = sprites.create(img`
    ........................
    ..............fff.......
    .............f2fffff....
    ...........ff22eeeeeff..
    ..........ff222eeeeeeff.
    ..........feeeefffeeeef.
    .........fe2222eeefffff.
    .........f2efffff222efff
    ..cc.....fffeeefffffffff
    ..cdcc...fee44fbbe44efef
    ..ccddcc..feddfbb4d4eef.
    ....cdddceefddddd4eeef..
    .....ccdcddee2222222f...
    ......cccdd44e544444f...
    .........eeeeffffffff...
    .............ff...fff...
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
controller.moveSprite(knight)
